use MAR

CREATE TABLE PRESIDENTE
(
ID_PRESIDENTE INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(50)
)


CREATE TABLE AUTOR
(
ID_AUTOR INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(20),
SOBRENOME VARCHAR(20) ,
TFC INT,
CONSTRAINT FK_AUTOR_TFC FOREIGN KEY (TFC) REFERENCES AUTOR (ID_AUTOR)
)
CREATE TABLE TFC
(
ID_TFC INT PRIMARY KEY IDENTITY (1,1),
TITULO VARCHAR(40),
CO_ORIENTADOR VARCHAR(50),
ORIENTADOR VARCHAR(50) ,
)
select * from AVALIACAO
CREATE TABLE AVALIACAO
(
ID_AVALIACAO
 INT PRIMARY KEY IDENTITY(1,1),
 INTRODUCAO_P int,
 INTRODUCAO_O int,
 INTRODUCAO_V int,
 MEDIA_I  AS INTRODUCAO_P*1+INTRODUCAO_O*0.75+INTRODUCAO_V*0.25/INTRODUCAO_P+INTRODUCAO_O+INTRODUCAO_V,
METODOLOGIA_P int,
 METODOLOGIA_O int,
METODOLOGIA_V int,
 MEDIA_M  AS METODOLOGIA_P*2+METODOLOGIA_O*1.25+METODOLOGIA_V*0.75/METODOLOGIA_P+METODOLOGIA_O+METODOLOGIA_V,
REFERENCIAL_P int,
REFERENCIAL_O int,
REFERENCIAL_V int,
 MEDIA_R  AS REFERENCIAL_P*1+REFERENCIAL_O*0.75+REFERENCIAL_V*0.25/REFERENCIAL_P+REFERENCIAL_O+REFERENCIAL_V,
ANALISE_P int,
ANALISE_O int,
ANALISE int,
 MEDIA_A  AS ANALISE_P*4+ANALISE_O*2.5+ANALISE*1.5/ANALISE_P+ANALISE_O+ANALISE,
CONCLUSAO_P int,
CONCLUSAO_O int,
CONCLUSAO_V int,
 MEDIA_C  AS CONCLUSAO_P*1+CONCLUSAO_O*0.75+CONCLUSAO_V*0.25/CONCLUSAO_P+CONCLUSAO_O+CONCLUSAO_V,
COMPRIMENTO_P int,
COMPRIMENTO_O int,
COMPRIMENTO_V int,
 MEDIA_CO  AS COMPRIMENTO_P*1+COMPRIMENTO_O*0.75+COMPRIMENTO_V*0.25/COMPRIMENTO_P+COMPRIMENTO_O+COMPRIMENTO_V,
 media_final as (INTRODUCAO_P*1+INTRODUCAO_O*0.75+INTRODUCAO_V*0.25/INTRODUCAO_P+INTRODUCAO_O+INTRODUCAO_V+METODOLOGIA_P*2+METODOLOGIA_O*1.25+METODOLOGIA_V*0.75/METODOLOGIA_P+METODOLOGIA_O+METODOLOGIA_V+REFERENCIAL_P*1+REFERENCIAL_O*0.75+REFERENCIAL_V*0.25/REFERENCIAL_P+REFERENCIAL_O+REFERENCIAL_V+ANALISE_P*4+ANALISE_O*2.5+ANALISE*1.5/ANALISE_P+ANALISE_O+ANALISE+CONCLUSAO_P*1+CONCLUSAO_O*0.75+CONCLUSAO_V*0.25/CONCLUSAO_P+CONCLUSAO_O+CONCLUSAO_V+COMPRIMENTO_P*1+COMPRIMENTO_O*0.75+COMPRIMENTO_V*0.25/COMPRIMENTO_P+COMPRIMENTO_O+COMPRIMENTO_V)/6,
 AUTOR INT,
 PRESIDENTE INT,
 ORIENTADOR INT,
 VOGAL INT,
 CONSTRAINT FK_AVALIACAO_AUTOR FOREIGN KEY (AUTOR) REFERENCES AUTOR(ID_AUTOR),
 CONSTRAINT FK_AVALIACAO_PRESIDENTE FOREIGN KEY (PRESIDENTE) REFERENCES PRESIDENTE(ID_PRESIDENTE),
 CONSTRAINT FK_AVALIACAO_TB_ORIENTADOR FOREIGN KEY (ORIENTADOR) REFERENCES TB_ORIENTADOR(ID_ORIENTANDOR),
 CONSTRAINT FK_AVALIACAO_TB_VOGAL FOREIGN KEY (VOGAL) REFERENCES TB_VOGAL(ID_VOGAL)
 )
 
 CREATE TABLE TB_ORIENTADOR
 (
 ID_ORIENTANDOR INT PRIMARY KEY IDENTITY (1,1),
 ORIENTADOR VARCHAR (40)
 )

 CREATE TABLE TB_VOGAL
 (
 ID_VOGAL INT PRIMARY KEY IDENTITY (1,1),
 VOGAL VARCHAR (40)
 )

 SELECT *FROM AVALIACAO